<?php  echo $this->doctype(); ?>

   <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

<!-- Template stylesheet -->
<link href="/css/screen.css" rel="stylesheet" type="text/css" media="all">
<link href="/js/visualize/visualize.css" rel="stylesheet" type="text/css" media="all">
<link href="/js/fancybox/jquery.fancybox-1.3.4.css" rel="stylesheet" type="text/css" media="all">

<!--[if IE]>
	<link href="css/ie.css" rel="stylesheet" type="text/css" media="all">
	<meta http-equiv="X-UA-Compatible" content="IE=7" />
<![endif]-->

<!-- Jquery and plugins -->
<script type="text/javascript" src="/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/js/ui/jquery-ui-1.8.9.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery.img.preload.js"></script>
<script type="text/javascript" src="/js/hint.js"></script>
<script type="text/javascript" src="/js/visualize/jquery.visualize.js"></script>
<script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.js"></script>
<script type="text/javascript" src="/js/custom_blue.js"></script>
<script type="text/javascript" charset="utf-8"> 
$(function(){ 
    // find all the input elements with title attributes
    $('input[title!=""]').hint();
    $('#login_info').click(function(){
		$(this).fadeOut('fast');
	});
});
</script>
</head>
<body class="login">

	<!-- Begin login window -->
	<div id="login_wrapper">
		<div class="message"><?php echo $this->messenger(); ?></div>

		<div id="login_top_window">
			<img src="../img/blue/top_login_window.png" alt="top window"/>
		</div>
		
		<!-- Begin content -->
		<div id="login_body_window">
			<div class="inner">
				<img src="../img/login_logo.png" alt="logo"/>
				<?=$this->form?>
			</div>
		</div>
		<!-- End content -->
		
		<div id="login_footer_window">
			<img src="../img/blue/footer_login_window.png" alt="footer window"/>
		</div>
		<div id="login_reflect">
			<img src="../img/blue/reflect.png" alt="window reflect"/>
		</div>
	</div>
	<!-- End login window -->
		
	</body>
</html>