
			<h1>SMS</h1>
			
			<!-- Begin shortcut menu -->
			<ul id="shortcut">
    			<li>
    			  <a href="modal_window.html" id="shortcut_home" title="Clique aqui para ir a Home">
				    <img src="../img/shortcut/home.png" alt="home"/><br/>
				    <strong>Home</strong>
				  </a>
				</li>
    			<li>
    			  <a href="modal_window.html" title="Clique aqui para ver os dados dos SMS's">
				    <img src="../img/shortcut/stats.png" alt="stats"/><br/>
				    <strong>Estatística</strong>
				  </a>
				</li>
				<li>
    			  <a href="modal_window.html" title="Click me to open modal window">
				    <img src="../img/shortcut/setting.png" alt="setting"/><br/>
				    <strong>Config.</strong>
				  </a>
				</li>
  			</ul>
			<!-- End shortcut menu -->
			<!-- Begin shortcut notification -->
			<div id="shortcut_notifications">
				<!-- <span class="notification" rel="shortcut_home">10</span>
				<span class="notification" rel="shortcut_contacts">5</span> -->
			</div>
			<!-- End shortcut noficaton -->			
			<br class="clear"/>
		<!-- Begin two column window -->
			
			<!-- Begin left column window -->
			<div class="twocolumn">
				<div class="column_left">
					<div class="header">
						<span>Mensagem</span>
					</div>
					<br class="clear"/>
					<div class="content">						
						<h2>Faça sua mensagem</h2>
						<p>
							<label>Assinatura:</label>
							<input type="text" name="from" id="from" value="<?=$this->assinatura_sms?>"/>
							<span id="char"></span>
						</p><br/>
						<p>
							<label class="msg">Mensagem: <span class="msg2">Prezado(a) <u>Cliente</u>,</span></label>
							<textarea id="mensagem" name="mensagem" rows="5" cols="30">para facilitar o seu credenciamento no curso de criação leve seu comprovante de pagamento. Obrigado!</textarea>
							<span id="char2"></span>
							<span class="description">A <b>assinatura</b> com a <b>mensagem</b> podem conter no máximo 140 caracteres.</span>
						</p>
						<br/><br/>
						<h2>Enviar para:</h2>
						<div id="loading_clientes_grupo" style="display:none"></div>
						<div id="x" style="display:none"></div>
						<div id="clientes_grupo">
						
						</div>
						<p>
							<input type="button" id="btn_modal" class="enviar_mensagem" value="Enviar mensagem"/>
						</p>
					</div>
				</div>
				<!-- End left column window -->
				
				<!-- Begin right column window -->
				<div class="column_right">
					<div class="header">
						<span>Clientes</span>
					</div>
					<br class="clear"/>
					<div class="content">
						<h2>Cadastro</h2>
						<div id="loading_cliente" style="display:none"></div>
						<form id="form_adicionar_cliente_sms" action="#" method="post">
						<p>
							<label>Nome:</label>
							<input type="text" id="nome" name="nome" class="nome"/>
						</p>
						<br/>
						<p>
							<label>E-mail:</label>
							<input type="text" id="email" name="email" class="email"/>
						</p>
						<br/>
						<p>
							<label>Celular:</label>
							<input type="text" id="celular" name="celular" class="celular"/>
						</p>
						<br/>
						<p>
							<label>Grupo:</label>
							<select id="select_grupo" name="grupo_id">
            	      				<option>Aguarde o carregamento</option>
            	    		</select>
							<a class="lft_input" href="#" id="novo_grupo" title="Adicionar grupo">Adicionar novo</a>
						</p>
						<br/>
						<p>
							<input type="submit" id="btn_modal" value="Salvar"/>
						</p>
						<br/>
						</form>
					</div>
				</div>
				<div class="column_right">
					<div class="header">
						<span>Relatório</span>
					</div>
					<br class="clear"/>
					<div class="content">
						<!-- Onde será apresentado o relatorio -->
						<div id="relatorio" style="width: 500px; height: 400px; margin: 0 auto">
						</div>
					</div>
				</div>
				<!-- End right column window -->
			</div>
			<!-- End two column window -->
			<div style="display:none">
				<div id="grupo">
					<form id="form_adicionar_grupo" action="#" method="post">
							<p>
								<label class="excessao">Nome do grupo:</label>
								<input type="text" name="nome" class="grupo"/>
							</p>
							<br/>
							<p>
								<input type="button" id="salvar_grupo" value="Salvar grupo"/>
							</p>
					</form>
				</div>
			</div>
			<div id="debug">
			</div>
			


