<section id="content">
		<div id="content-center" class="center">
			<div id="col-1" class="left">
				<header class="titulo">
					<h1>Certificados</h1>
				</header>
				<article>
					<p>Digite o seu CPF para gerar seu certificado.</p>
					<form id="formCertificado" name="formInscricao" class="wufoo topLabel page" enctype="multipart/form-data" method="post" action="/certificado" autocomplete="on">
						<ul>
						<li id="foli0" class=" complex    ">
								  
								 <span class="full">
								  <input id="cpf" name="cpf" type="text" class="field text addr"	value="" tabindex="1" />
								    <label for="cpf">CPF</label>
								</span>
						</li>
						<li class="buttons ">
							<div>
								<input id="saveForm" name="saveForm" type="submit" value="Gerar meu certificado" />
							</div>
						</li>
					</ul>
					</form>
				</article>
			</div>
			<aside class="right">
				<?php include('aside.php');?>
			</aside>
		</div>
	</section>