<section id="content">
		<div id="content-center" class="center">
			<div id="col-1" class="left">
				<header class="titulo">
					<h1>Contato</h1>
				</header>
				<article>
					<p>Para qualquer dúvida, sugestão ou problema em sua inscrição envie e-mail para <a href="mailto:<?=$this->emailContato?>"><?=$this->emailContato?></a>
					 ou para nossas redes socias <a href="<?=$this->twitter?>">twitter</a> e <a href="<?=$this->facebook?>">facebook</a></p>
					<strong>GCE-PI / GLEJ-PI</strong> </p>
					<p><strong>Endereço:</strong> Rua Magalhães Filho, 1270 - Marquês de Paranaguá<br/>
					<strong>CEP:</strong> 64002-450 - Teresina - Piauí - Brasil<br/></p>
					<p style="font-size:20px">Contatos com a Diretoria do GCE / GLEJ</p>
					<p><strong>MCE:</strong> Francisco Armínio: (89) 9930-0623 / 9938-0383  <br/>
					<strong>Secretário do Congresso:</strong> João Carlos: (89) 9929-4548<br/>
					<strong>Grande Mestre Estadual:</strong> Marcelo Leal: (86) 9916-2735<br/>
					<strong>Delegado de Comunicação:</strong> Cândido Sales: (86) 9933-5216 <br/>			
				</article>
				<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
			    <script>
					var map;
					function initialize() {
					  var mapOptions = {
					    zoom: 16,
					    center: new google.maps.LatLng(-5.078045, -42.812174),
					    mapTypeId: google.maps.MapTypeId.ROADMAP
					  };
					  map = new google.maps.Map(document.getElementById('map-canvas'),
					      mapOptions);

					  var marker = new google.maps.Marker({
					    map: map,
					    position: map.getCenter()
					  });
					  var infowindow = new google.maps.InfoWindow();
					  infowindow.setContent('<b>Picos</b>');
					  
					  google.maps.event.addListener(marker, 'click', function() {
					      infowindow.open(map, marker);
					  });
					}

					google.maps.event.addDomListener(window, 'load', initialize);

			    </script>
			    <div id="map-canvas"></div>
				</div>
			<aside class="right">
				<?php include('aside.php');?>
			</aside>
		</div>
</section>
