<section id="content">
		<div id="content-center" class="center">
			<div id="col-1" class="left">
				<header class="titulo">
					<h1>Contato</h1>
				</header>
				<article>
					<p>Para qualquer dúvida, sugestão ou problema em sua inscrição envie e-mail para <a href="mailto:<?=$this->emailContato?>"><?=$this->emailContato?></a>
					 ou para nossas redes socias <a href="<?=$this->twitter?>">twitter</a> e <a href="<?=$this->facebook?>">facebook</a></p>
					<strong>GCE-PI / GLEJ-PI</strong> </p>
					<p><strong>Endereço:</strong> Rua Magalhães Filho, 1270 - Marquês de Paranaguá<br/>
					<strong>CEP:</strong> 64002-450 - Teresina - Piauí - Brasil<br/></p>
					<p style="font-size:20px">Contatos com a Diretoria do GCE / GLEJ</p>
					<p><strong>MCE:</strong> Yan Walter: (86) 9925-6031 <br/>
					<strong>Secretário do Congresso:</strong> Mailson Carvalho: (86) 9435-9945 <br/>
					<strong>Delegado de Comunicação:</strong> Cândido Sales: (86) 9933-5216 / (86) 8868-8861 <br/>
					<strong>Secretário Executivo:</strong> Rafael Lustosa: (86) 8815-2651 </p>	
			
				</article>
				<!-- <div class="maps">
					<iframe width="520" height="450" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com.br/maps?f=q&amp;source=s_q&amp;hl=pt-BR&amp;geocode=&amp;q=sinapro+piau%C3%AD&amp;aq=&amp;sll=-5.089245,-42.812573&amp;sspn=0.005568,0.010568&amp;gl=br&amp;ie=UTF8&amp;hq=sinapro&amp;hnear=Piau%C3%AD&amp;t=m&amp;cid=1389854752994845172&amp;ll=-5.052899,-42.781792&amp;spn=0.038474,0.044546&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com.br/maps?f=q&amp;source=embed&amp;hl=pt-BR&amp;geocode=&amp;q=sinapro+piau%C3%AD&amp;aq=&amp;sll=-5.089245,-42.812573&amp;sspn=0.005568,0.010568&amp;gl=br&amp;ie=UTF8&amp;hq=sinapro&amp;hnear=Piau%C3%AD&amp;t=m&amp;cid=1389854752994845172&amp;ll=-5.052899,-42.781792&amp;spn=0.038474,0.044546&amp;z=14&amp;iwloc=A" style="color:#0000FF;text-align:left">Exibir mapa ampliado</a></small>
				</div>-->
				</div>
			<aside class="right">
				<?php include('aside.php');?>
			</aside>
		</div>
</section>
