<section id="content">
		<div id="content-center" class="center">
			<div id="col-1" class="left">
				<header class="titulo">
					<h1>Hospedagem</h1>
				</header>
				<!--<article>
					<p>Abaixo segue uma lista de bons hóteis para você se hospedar durante o período do evento:</p>
				</article>
				<img id="conquistar" width="140" height="80" src="/img/staff/miraceu-turismo.png"></img>
				<p id="conquistar-info">Compre suas passagens através de nosso parceiro <strong>Miracéu Turismo</strong><br/>
					<strong>Endereço:</strong> Rua Sete de Setembro, 159 - Centro, Teresina - PI, 64000-210<br/>
					<strong>Telefone:</strong> (86) 2106-3388 / (86) 9987-7782 / (86) 9967-6714 (Com a Patrícia Dias)
				</p>-->
				
				<!--<div class="hotel highlight">
				<h2>Sede do Congresso</h2>
					<img widht="110" height="135" src="/img/hoteis/formula-flat.jpg"></img>
					<h3>
						<a title="Hotel Fórmula Flat Europa" href="http://www.formulaflateuropa.com.br/" target="_blank">Hotel Fórmula Flat Europa</a>
					</h3>
					<p><strong>Site:</strong> <a href="http://www.formulaflateuropa.com.br/">http://www.formulaflateuropa.com.br/</a><br/>
					   <strong>Telefone:</strong> (86) 3223-7100 <br/>
					   <!--<strong>Distância para o evento:</strong> 4,4 km</p>
					  <a href="http://maps.google.com.br/maps?saddr=Av.+Fr+Serafim,+1696+-+Teresina+-+PI,+64001-020+(Metropolitan+Hotel)&daddr=Av.+Ns.+de+F%C3%A1tima&hl=pt-BR&ie=UTF8&sll=-5.082309,-42.819214&sspn=0.049501,0.084543&geocode=FWpVsv8dScZy_SFPjTQRRqLs4A%3BFT2Vsv8dhQ1z_Q&vpsrc=0&mra=ls&t=m&z=15" target="_blank" title="Clique e saiba a distância entre os locais">
							<img class="distancia" widht="190" height="135" src="/img/distancia/metropolitan.jpg"></img>
					</a>-->
				<!--</div>
				<h2>Outras opções</h2>-->
				<div class="hotel">
					<img widht="135" height="135" src="/img/hoteis/picos-hotel.jpg"></img>
					<h3>
						<a title="Picos Hotel" href="http://www.picoshotel.com/" target="_blank">Picos Hotel</a>
					</h3>
					<p><strong>Site:</strong> <a href="http://www.picoshotel.com/">http://www.picoshotel.com/</a><br/>
					   <strong>Telefone:</strong> (89) 3422-5214 <br/>
					   <!--<strong>Distância para o evento:</strong> 4,4 km</p>
					  <a href="http://maps.google.com.br/maps?saddr=Av.+Fr+Serafim,+1696+-+Teresina+-+PI,+64001-020+(Metropolitan+Hotel)&daddr=Av.+Ns.+de+F%C3%A1tima&hl=pt-BR&ie=UTF8&sll=-5.082309,-42.819214&sspn=0.049501,0.084543&geocode=FWpVsv8dScZy_SFPjTQRRqLs4A%3BFT2Vsv8dhQ1z_Q&vpsrc=0&mra=ls&t=m&z=15" target="_blank" title="Clique e saiba a distância entre os locais">
							<img class="distancia" widht="190" height="135" src="/img/distancia/metropolitan.jpg"></img>
					</a>-->
				</div>
				<div class="hotel">
					<img widht="135" height="135" src="/img/hoteis/entre-rios.jpg"></img>
					<h3>
						<a title="Entre Rios Hotel" href="http://www.entrerioshotel.com.br/" target="_blank">Entre Rios Hotel</a>
					</h3>
					<p><strong>Site:</strong> <a href="http://www.entrerioshotel.com.br/">http://www.entrerioshotel.com.br/</a><br/>
					<strong>Telefone:</strong> (89) 3422-6677<br/>
					<!--<strong>Distância para o evento:</strong> 5,5 km</p>
					 <a href="http://maps.google.com.br/maps?saddr=Luxor+Piau%C3%AD+Hotel+-+Teresina+-+PI&daddr=Av.+Ns.+de+F%C3%A1tima&hl=pt-BR&ie=UTF8&ll=-5.080942,-42.801747&spn=0.02475,0.042272&sll=-5.08145,-42.79777&sspn=0.02475,0.042272&geocode=FSRasv8dEbZy_SGObgd5gPrHiw%3BFT2Vsv8dhQ1z_Q&vpsrc=6&mra=ls&t=m&z=15" target="_blank" title="Clique e saiba a distância entre os locais">
							<img class="distancia" widht="190" height="135" src="/img/distancia/luxor.jpg"></img>
					</a>-->
				</div>
				 <!-- <div class="hotel">
					<img widht="110" height="135" src="/img/hoteis/lord.jpg"></img>
					<h3>
						<a title="Lord Hotel" href="http://www.lordhotel.com.br/" target="_blank">Lord Hotel</a>
					</h3>
					<p><strong>Site:</strong> <a href="http://www.lordhotel.com.br/">http://www.lordhotel.com.br/</a><br/>
					   <strong>Telefone:</strong> (86) 2106-5500<br/>
					 <strong>Distância para o evento:</strong> 8,8 km</p>
					<a href="http://maps.google.com.br/maps?saddr=Lord+Hotel+-+Teresina+-+PI&daddr=Av.+Ns.+de+F%C3%A1tima&hl=pt-BR&ie=UTF8&sll=-5.080942,-42.801747&sspn=0.02475,0.042272&geocode=FXPKsf8dGepy_SFYFcqA4nI1gymLVHb-2zaOBzGOepasmUNI1w%3BFT2Vsv8dhQ1z_Q&vpsrc=0&mra=ls&t=m&z=13" target="_blank" title="Clique e saiba a distância entre os locais">
							<img class="distancia" widht="190" height="135" src="/img/distancia/lord.jpg"></img>
					</a>
				</div>-->
				<div class="hotel">
					<img widht="110" height="135" src="/img/hoteis/rio-guaribas.jpg"></img>
					<h3>
						<a title="Hotel Rio Guaribas" href="https://plus.google.com/112875721844466688978/about?gl=br&hl=pt-BR" target="_blank">Hotel Rio Guaribas</a>
					</h3>
					<p><strong>Site:</strong> <a href="https://plus.google.com/112875721844466688978/about?gl=br&hl=pt-BR">https://plus.google.com/112875721844466688978/about?gl=br&hl=pt-BR</a><br/>
					   <strong>Telefone:</strong> (89) 3422-0708<br/>
					  <!--<strong>Distância para o evento:</strong> 5,4 km</p>
					<a href="http://maps.google.com.br/maps?saddr=Rio+Poty+Hotel+-+Teresina+-+PI&daddr=Av.+Ns.+de+F%C3%A1tima&hl=pt-BR&ie=UTF8&ll=-5.081668,-42.794194&spn=0.02475,0.042272&sll=-5.067861,-42.802219&sspn=0.024751,0.042272&geocode=FYdgsv8d3QVz_SEFkxAbd7wU3A%3BFT2Vsv8dhQ1z_Q&vpsrc=0&mra=ls&t=m&z=15" target="_blank" title="Clique e saiba a distância entre os locais">
							<img class="distancia" widht="190" height="135" src="/img/distancia/riopoty.jpg"></img>
					</a>-->
				</div>
				<div class="hotel">
					<h3>
						<a title="Hotel Grande Rio" href="http://www.guiamais.com.br/local/hotel+grande+rio-hoteis-picos-pi-12160573-11" target="_blank">Hotel Grande Rio</a>
					</h3>
					<p><strong>Site:</strong> <a href="http://www.guiamais.com.br/local/hotel+grande+rio-hoteis-picos-pi-12160573-11">http://www.guiamais.com.br/local/hotel+grande+rio-hoteis-picos-pi-12160573-11</a><br/>
					   <strong>Telefone:</strong> (89) 3422-3954<br/>
					  <!-- <strong>Distância para o evento:</strong> 3,7 km</p>
					<a href="http://maps.google.com.br/maps?saddr=Ibis+Hotel+-+Teresina+-+PI&daddr=Av.+Ns.+de+F%C3%A1tima&hl=pt-BR&ie=UTF8&ll=-5.067861,-42.802219&spn=0.024751,0.042272&sll=-5.081675,-42.79418&sspn=0.02475,0.042272&geocode=FUqmsv8dQrpy_SH0q70M2FG_Vw%3BFT2Vsv8dhQ1z_Q&vpsrc=0&mra=ls&t=m&z=15" target="_blank" title="Clique e saiba a distância entre os locais">
							<img class="distancia" widht="190" height="135" src="/img/distancia/ibis.jpg"></img>
					</a> --> 
				</div>
			</div>
			<aside class="right">
				<?php include('aside.php');?>
			</aside>
		</div>
	</section>
