
	<!-- <form id="formInscrito" class="appnitro"  method="post" action="/index/notificacao-pagseguro">
		<input type="hidden" value="_Ab123" name="id_transacao"/>
		<input type="hidden" value="transaction" name="notificationType"/>
		<input type="hidden" value="2" name="status"/>
		<input type="hidden" value="60000" name="valor"/>
		<input type="hidden" value="0" name="cod_moip"/>
		<input type="hidden" value="candidosg@gmail.com" name="sender_email"/>
		
		<input type="submit" value="Testar"/>					
	</form>-->