
	<!-- <form id="formInscrito" class="appnitro"  method="post" action="/index/notificacao-moip">
		<input type="hidden" value="_Ab123" name="id_transacao"/>
		<input type="hidden" value="1" name="forma_pagamento"/>
		<input type="hidden" value="4" name="status_pagamento"/>
		<input type="hidden" value="BoletoBancario" name="tipo_pagamento"/>
		<input type="hidden" value="60000" name="valor"/>
		<input type="hidden" value="0" name="cod_moip"/>
		<input type="hidden" value="candidosg@gmail.com" name="email_consumidor"/>
		
		<input type="submit" value="Testar"/>					
	</form>-->