<section id="content">
		<div id="content-center" class="center">
			<div id="col-1" class="left">
				<header class="titulo">
					<h1>Notícias</h1>
				</header>
				<article>
					<p>Acesse os principais portais de notícia do nosso estado.</p>
					<ul class="noticias">
						<li>
							<a title="180 Graus" href="http://180graus.com/" target="_blank">
								<img width="150" height="79" src="/img/noticias/180graus.jpg"></img>
							</a>
						</li>
						<li>
							<a title="Acesse Piauí" href="http://www.acessepiaui.com.br/" target="_blank">
								<img width="150" height="79" src="/img/noticias/acessepiaui.jpg"></img>
							</a>
						</li>
						<li>
							<a title="Cidade Verde" href="http://www.cidadeverde.com/" target="_blank">
								<img width="150" height="79" src="/img/noticias/cidadeverde.jpg"></img>
							</a>
						</li>
						<li>
							<a title="Portal AZ" href="http://www.portalaz.com.br/" target="_blank">
								<img width="150" height="79" src="/img/noticias/portalaz.jpg"></img>
							</a>
						</li>
						<li>
							<a title="Meio Norte" href="http://www.meionorte.com/" target="_blank">
								<img width="150" height="79" src="/img/noticias/meionorte.jpg"></img>
							</a>
						</li>
						<li>
							<a title="Portal O Dia" href="http://www.portalodia.com/" target="_blank">
								<img width="150" height="79" src="/img/noticias/portalodia.jpg"></img>
							</a>
						</li>
						<li>
							<a title="GP1" href="http://www.gp1.com.br/" target="_blank">
								<img width="150" height="79" src="/img/noticias/gp1.jpg"></img>
							</a>
						</li>
						

					</ul>
				</article>
			</div>
			<aside class="right">
				<?php include('aside.php');?>
			</aside>
		</div>
</section>