<section id="content">
		<div id="content-center" class="center">
			<div id="col-1" class="left">
				<header class="titulo">
					<h1>Palestrantes</h1>
					<p class="sub-titulo">Em breve.</p>
				</header>
			<!-- 	<article class="palestrantes">
					<img width="144" height="174" src="/img/palestrantes/s.png"></img>
					<h3><a id="aba" title="Site da ABA" href="http://www.aba.com.br" target="_blank">Com a presença do Presidente / Vice Presidente da ABA - Associação Brasileira de Anunciantes </a></h3>
					<p><a href="http://www.aba.com.br">http://www.aba.com.br</a></p>
				</article>
				<article class="palestrantes">
					<img width="144" height="174" src="/img/palestrantes/lino.png"></img>
					<h3><a id="lino" title="" href="#" target="_blank">Antônio Lino Pinto</a></h3>
					<p>É administrador, com especialização em finanças e administração, sócio da Talent Comunicação e Planejamento S/A., diretor do Sinapro-SP, diretor da  Fenapro e Vice presidente da ABAP, autor do livro; Pequenas Agências, Grandes Resultados-Como gerenciar na prática as finanças de uma agência de propaganda. Lançado pela Clio Editora. </p>
				</article>	-->			
			</div>
			<aside class="right">
				<?php include('aside.php');?>
			</aside>
		</div>
</section>
