<section id="content">
		<div id="content-center" class="center">
			<div id="col-1" class="left">
				<header class="titulo">
					<h1>Programação</h1>
				</header>
			    <article class="col-2">
					<h3>Sexta-feira 06/12</h3>
					<ul>
						<li class="hour">13h às 18h</li>
						<li class="title">Credenciamento e entrega dos Kit’s</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">18h30 às 20h</li>
						<li class="title">Jantar</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">20h às 21h</li>
						<li class="title"> Abertura Oficial do XI CEODPI</li>
						<li>Traje: Camisa do Congresso</li>
					</ul>
					<ul>
						<li class="hour">21h30</li>
						<li class="title">Investidura ao Grau Cavaleiro e Grau Capela</li>
						<li>Traje: DeMolay Completo</li>
					</ul>
				</article>
				<article class="col-2">
					<h3>Sábado 07/12</h3>
					<ul>
						<li class="hour">6h30 às 08h</li>
						<li class="title">Café da manhã </li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">08h30 às 12h</li>
						<li class="title">Abertura Oficial da Copa de Futsal “Alberto Mansur”</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">12h às 12h30</li>
						<li class="title">Premiações da Copa de Futsal</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">12h30 as 14h</li>
						<li class="title">Almoço</li>
						<li>Traje: Camisa do Congresso (obrigatória!)</li>
					</ul>
					<ul>
						<li class="hour">14h às 15h</li>
						<li class="title">Palestra – Tema: Como falar em Público – Palestrante: Ir. Samuel Lima</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">15h às 16h</li>
						<li class="title">I Concurso Estadual de Redação</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">16h às 16h30</li>
						<li class="title"> Espaço reservado para Alumni Brasil</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">17h às 18h30</li>
						<li class="title"> Assembleia Estadual do Grande Capítulo Estadual do Piauí</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">18h30às 20h</li>
						<li class="title"> Jantar</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">20h30</li>
						<li class="title"> Grau Cavaleiro da Cruz de Salém e Ex-templário</li>
						<li>Traje: Livre</li>
					</ul>
				</article>
				<article class="col-3">
					<h3>Domingo 08/12</h3>
					<ul>
						<li class="hour">06h30 às 8h</li>
						<li class="title">Café da manhã</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">9h às 12h</li>
						<li class="title">Encerramento e Posse da Liderança Adulta e Juvenil</li>
						<li>Traje: DeMolay Completo</li>
					</ul>
					<ul>
						<li class="hour">12h</li>
						<li class="title"> Almoço e despedida dos congressistas </li>
						<li>Traje: Livre</li>
					</ul>
				</article>
			</div>
			<aside class="right">
				<?php include('aside.php');?>
			</aside>
		</div>
</section>