<section id="content">
		<div id="content-center" class="center">
			<div id="col-1" class="left">
				<header class="titulo">
					<h1>Programação</h1>
				</header>
			    <article class="col-2">
					<h3>Em breve</h3>
					<!--
					<ul>
						<li class="hour">18h às 19h</li>
						<li class="title">Coffee-Break e Credenciamento [<a href="http://goo.gl/maps/wd0h6" title="Mapa do Hotel">Hotel Fórmula Flat</a>]</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">20h às 21h</li>
						<li class="title">Cerimônia de Abertura do Congresso [<a href="http://goo.gl/maps/BXm6o" title="Mapa do Centro de Artesanato">Centro de Artesanato</a>]</li>
						<li>Traje: DeMolay Completo</li>
					</ul>
					<ul>
						<li class="hour">21h às 22h</li>
						<li class="title">Apresentação da Orquestra Sinfônica de Teresina e João Claúdio Moreno [<a href="http://goo.gl/maps/BXm6o" title="Mapa do Centro de Artesanato">Centro de Artesanato</a>]</li>
						<li>Traje: DeMolay Completo</li>
					</ul>
					<ul>
						<li class="hour">22h às 22h30</li>
						<li class="title">Coquetel de Abertura [<a href="http://goo.gl/maps/BXm6o" title="Mapa do Centro de Artesanato">Centro de Artesanato</a>]
						</li>
						<li>Traje: DeMolay Completo</li>
					</ul>
					<ul>
						<li class="hour">23h</li>
						<li class="title">Concessão dos Graus Históricos (Capela e Cruz de Salém) [<a href="http://goo.gl/maps/wd0h6" title="Mapa do Hotel">Hotel Fórmula Flat</a>]</li>
						<li>Traje: DeMolay Completo</li>
					</ul>
				</article>
				<article class="col-2">
					<h3>Sábado 22/09</h3>
					<ul>
						<li class="hour">8h às 9h</li>
						<li class="title">Café da manhã [<a href="http://goo.gl/maps/wd0h6" title="Mapa do Hotel">Hotel Fórmula Flat</a>]</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">9h às 11h</li>
						<li class="title">Gincana das Virtudes [Auditório Fórmula]</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">11h às 13h</li>
						<li class="title">Almoço [<a title="Mapa da ARCA" href="http://goo.gl/maps/aOQNV" target="_blank">ARCA</a>]</li>
						<li>Traje: Camisa do Congresso (obrigatória!)</li>
					</ul>
					<ul>
						<li class="hour">13h30 às 14h30</li>
						<li class="title">CityTour - Passeio turístico por Teresina</li>
						<li>Traje: Camisa do Congresso (obrigatória!)</li>
					</ul>
					<ul>
						<li class="hour">15h às 16h30</li>
						<li class="title">Torneio Ritualístico [Auditório Fórmula]</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">16h30 às 18h</li>
						<li class="title">Desencontro dos Líderes [Auditório Fórmula]</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">18h às 20h</li>
						<li class="title">Assembléia [Auditório Fórmula]</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">20h às 21h</li>
						<li class="title">Jantar [Auditório Fórmula]</li>
						<li>Traje: Livre</li>
					</ul>
				</article>
				<article class="col-3">
					<h3>Domingo 23/09</h3>
					<ul>
						<li class="hour">7h30 às 9h</li>
						<li class="title">Café da manhã [Auditório Fórmula]</li>
						<li>Traje: Livre</li>
					</ul>
					<ul>
						<li class="hour">9h30 às 11h30</li>
						<li class="title">Posse GME, MCE, Of. Exec. e MCR’s – Homenagens [Auditório Fórmula]</li>
						<li>Traje: DeMolay Completo</li>
					</ul>
					<ul>
						<li class="hour">11h30 às 12h</li>
						<li class="title">Encerramento [Auditório Fórmula]</li>
						<li>Traje: DeMolay Completo</li>
					</ul>
					<ul>
						<li class="hour">12h às 13h</li>
						<li class="title">Almoço e  despedida das comitivas [<a title="Mapa da ARCA" href="http://goo.gl/maps/aOQNV" target="_blank">ARCA</a>]</li>
						<li>Traje: Livre</li>
					</ul>-->
				</article>
			</div>
			<aside class="right">
				<?php include('aside.php');?>
			</aside>
		</div>
</section>