<section id="content">
		<div id="content-center" class="center">
			<div id="col-1" class="left">
				<header class="titulo">
					<h1>Teresina</h1>
				</header>
				<article class="teresina">
					<p>A cidade de Teresina é uma das capitais mais calorosas do Brasil.</p>
					<p>Faz sol de janeiro a janeiro e o calor é humano é a marca registrada da nossa gente.</p>
					<p>Além das belezas naturais e da hospitalidade que é nosso cartão de visita.</p>
					<p>Em setembro de 2012, a cidade verde vai ser sede do X Congresso da Ordem DeMolay e contará com grandes nomes da liderança juvenil nacional.</p>
					<p>Veja abaixo algumas fotos de Teresina:</p>
				</article>
				<div class="flickr teresina">
					<script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?count=7&amp;display=random&amp;size=s&amp;layout=h&amp;source=all_tag&tag=teresina por do sol"></script>
				</div>
				<article>
				<p>Acesse os sites e conheça as notícias sobre a nossa Prefeitura Municipal de Teresina, do Governo do Estado do Piauí e da Assembléia Legislativa.</p>
				<ul class="teresina_orgaos">
						<li>
							<a title="Prefeitura Municipal de Teresina" href="http://www.teresina-pi-gov.com.br/" target="_blank">
								<img width="150" height="79" src="/img/noticias/prefeitura.png"></img>
							</a>
						</li>
						<li>
							<a title="Governo do Estado do Piauí" href="http://www.piaui.pi.gov.br/" target="_blank">
								<img width="150" height="79" src="/img/noticias/governo.png"></img>
							</a>
						</li>
						<li>
							<a title="Assembléia Legislativa do Piauí" href="http://www.alepi.pi.gov.br/" target="_blank">
								<img width="150" height="79" src="/img/noticias/alepi.jpg"></img>
							</a>
						</li>
				</ul>
				</article>
				<iframe width="520" height="450" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com.br/maps?f=q&amp;source=s_q&amp;hl=pt-BR&amp;geocode=&amp;q=teresina&amp;aq=&amp;sll=-27.590229,-48.56122&amp;sspn=0.079874,0.169086&amp;vpsrc=0&amp;ie=UTF8&amp;hq=&amp;hnear=Teresina+-+Piau%C3%AD&amp;z=13&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com.br/maps?f=q&amp;source=embed&amp;hl=pt-BR&amp;geocode=&amp;q=teresina&amp;aq=&amp;sll=-27.590229,-48.56122&amp;sspn=0.079874,0.169086&amp;vpsrc=0&amp;ie=UTF8&amp;hq=&amp;hnear=Teresina+-+Piau%C3%AD&amp;z=13&amp;iwloc=A" style="color:#0000FF;text-align:left">Exibir mapa ampliado</a></small>
			</div>
			<aside class="right">
				<?php include('aside.php');?>
			</aside>
		</div>
</section>