<?php  echo $this->doctype(); ?>

<html>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <link href="/img/favicon.png" rel="shortcut icon" type="image/x-icon" />
        <link href='http://fonts.googleapis.com/css?family=Questrial|Montserrat:400,700' rel='stylesheet' type='text/css'>
        <link type="text/css" rel="stylesheet" href="/css/jquery-ui-1.8.12.custom.css" >
		<link rel="stylesheet/less" type="text/css" href="/css/style.less" media="all">
		<script src="/js/less-1.4.1.min.js" type="text/javascript"></script>
		<!--[if lt IE 9]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
        <?php flush(); ?>        
	</head>
	<body>
		<div id="message"><?php echo $this->messenger(); ?></div>
		<header id="other_pages" >
			<!--<div id="canto-superior">
				<img widht="184" height="184" src="/img/canto_superior.png"></img>
			</div>-->
			<section class="center">
				<a href="/">
					<img id="logo" width="330" height="120" src="/img/logo_mini.png"/>
				</a>
			</section>
			<nav>
				<div id="nav-center" class="center">
					<ul>
						<li>
							<a title="" href="/">O Congresso</a>
						</li>
						<li>
							<a title="" href="/inscricao">Inscrição</a>
						</li>
						<li>
							<a title="" href="/programacao">Programação</a>
						</li>
						<li>
							<a title="" href="/sede">Sede</a>
						</li>
						<li>
							<a title="" href="/hospedagem">Hospedagem</a>
						</li>
						<li>
							<a title="" href="/noticias">Notícias</a>
						</li>
						<li>
							<a title="" href="/contato">Contato</a>
						</li>
					</ul>
				</div>
			</nav>
		</header>
		<?php echo $this->layout()->content; ?>
		<footer>
		<section id="footer-center" class="center">
			<div class="col_2 left">
				<h4>Menu</h4>
					<ul>
						<li>
							<a title="" href="/">O Congresso</a>
						</li>
							<li>
								<a title="" href="/inscricao">Inscrição</a>
							</li>
							<li>
								<a title="" href="/programacao">Programação</a>
							</li>
							<li>
								<a title="" href="/teresina">Teresina</a>
							</li>
							<li>
								<a title="" href="/hospedagem">Hospedagem</a>
							</li>
							<li>
								<a title="" href="/noticias">Notícias</a>
							</li>
							<li>
								<a title="" href="/contato">Contato</a>
							</li>
					</ul>
			</div>
			<div class="col_2 left">
				<h4>Álbum de fotos</h4>
					<div class="flickr">
						<iframe src="http://www.intagme.com/in/?u=Y2VvZHBpfHNsfDMwMHwzfDN8fHllc3w1fHVuZGVmaW5lZA==" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:315px; height: 315px" ></iframe>
						<!--
						<script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?count=6&amp;display=latest&amp;size=s&amp;layout=h&amp;source=user&amp;user=78403060@N05"></script>-->
					</div>
			</div>
			<div class="col_2_r">
				<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like-box" data-href="http://www.facebook.com/ceodpi" data-width="292" data-show-faces="true" data-stream="false" data-header="false"></div>
			</div>
			<div class="line"></div>
			<div class="extra">
					<p class="author">Criação e Desenvolvimento: <a href="http://www.about.me/candidosales" title="Cândido Sales" target="_blank">Cândido Sales</a></p>
				</div>
		</section>
		
	<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-15472644-22']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
	<script src="/js/jquery-1.10.2.min.js" ></script>
	<script src="/js/jquery-ui-1.10.3/js/jquery-ui-1.10.3.custom.min.js" ></script>
	<script src="/js/jquery.maskedinput.1.3.1.min.js" ></script>
	<script src="/js/jquery.validate.1.8.1.min.js" ></script>
	<script type="text/javascript">
			$('.error_message, .success_message, .info_message, .warning_message').click(function(){
				$(this).fadeOut('fast');
			});
			
			$('.message').click(function(){
				$(this).fadeOut('fast');
			});

		 function muda(x){			 
				if(x == '2'){
					$('li#2').css('display','block');
					$('li#1').css('display','none');
				}else if(x == '1'){
					$('li#2').css('display','none');
					$('li#1').css('display','block');
				}
		 }
			
		var value = $("input[name$='tipo']").val();
		muda(value);

		$('#filiado').change(function() {
			$('.tipo_filiado').css('display','none');
			
			if($(this).attr('checked')){
				$('.tipo_filiado').css('display','block');
			}
		}); 
		 
		$("input[name$='tipo']").change(function() {
				var val = $(this).val();
				muda(val);
			}); 
				
		   $("#cep").mask("99.999-999");
		   $("#cpf").mask("999.999.999-99");   
		   $("#celular").mask("(99) 9999-9999");
		   $("#data_nasc").mask("99/99/9999"); 

			$("#formInscricao").validate({
				rules: {
					nome: {
						required: true,
						minlength: 4
					},
					cpf: {
						required: true,
						minlength: 11
					},
					rg: {
						required: true,
						minlength: 4
					},
					endereco: {
						required: true,
						minlength: 6
					},
					email: {
						required: true,
						email: true
					},
					celular: {
						required: true,
						minlength: 11
					},
					agree: "required"
				},
				messages: {
					nome: {
						required: "Por favor, insira seu nome",
						minlength: "Seu nome deve conter no mínimo 4"
					},
					cpf: {
						required: "Por favor, insira seu cpf",
						minlength: "Seu cpf deve conter no mínimo 11"
					},
					rg: {
						required: "Por favor, insira seu rg",
						minlength: "Seu rg deve conter no mínimo 4"
					},
					endereco: {
						required: "Por favor, insira seu endereco",
						minlength: "Seu endereco deve conter no mínimo 6"
					},
					email: "Por favor insira um e-mail válido",
					celular: {
						required: "Por favor, insira seu celular",
						minlength: "Seu celular deve conter no mínimo 11"
					},
					agree: "Please accept our policy"
				}
			});

			$("#formCertificado").validate({
				rules: {
					cpf: {
						required: true,
						minlength: 11
					},
				},
				messages: {
					cpf: {
						required: "Por favor, insira seu cpf",
						minlength: "Seu cpf deve conter no mínimo 11"
					},
				}
			});


	ajaxSegundaVia = {

			buscarCliente:function(dados){
				   
			       $.ajax({
		               url:'/index/ajax-buscar-cliente',
		               dataType:'json',
		               data: dados,
		               type:'POST',
		               success: function(data,textStatus){	
							console.log(data);
			               		               
		            	   if(data.valor=='1'){
		            		   console.log('Sucesso');
		            		   $('#formBuscaCPF').hide();
		            		   $('#formSegundaVia').show();

		            		   $('input[name="id_carteira"]').val(data.id_carteira);
		            		   $('input[name="nome"]').val(data.nome);
		            		   $('input[name="descricao"]').val(data.descricao);
		            		   $('input[name="id_transacao"]').val(data.id_transacao);
		            		   $('input[name="pagador_nome"]').val(data.pagador_nome);
		            		   $('input[name="pagador_email"]').val(data.pagador_email);
		            		   $('input[name="pagador_cep"]').val(data.pagador_cep);
		            		   $('input[name="pagador_logradouro"]').val(data.pagador_logradouro);
		            		   $('input[name="pagador_numero"]').val(data.pagador_numero);
		            		   $('input[name="pagador_cidade"]').val(data.pagador_cidade);
		            		   $('input[name="pagador_estado"]').val(data.pagador_estado);
		            		   $('input[name="pagador_bairro"]').val(data.pagador_bairro);
		            		   $('input[name="pagador_cpf"]').val(data.pagador_cpf);
		            		   $('input[name="pagador_rg"]').val(data.pagador_rg);
		            		   $('input[name="pagador_telefone"]').val(data.pagador_telefone);
		            		   $('input[name="valor"]').val(data.valor_transacao);

		            		   $('#segundaVia').val(data.pagador_nome+' - Gerar 2° via');

				           }else if(data.valor=='0'){
				           		console.log('Nao encontrou o cliente');
						   } 		 
		               },
		               error: function(XMLHttpRequest, textStatus, errorThrown){
		            	   console.log(textStatus+' '+errorThrown);
						}
		       });
			},
		}

			$("#formBuscaCPF").submit(function() {
			  ajaxSegundaVia.buscarCliente($("#formBuscaCPF").serialize());
			  event.preventDefault();
			});
    </script>
	</footer>
	</body>
</html>
	