<script type="text/javascript">
$(function(){
	$('#main-nav li:eq(12) a').addClass('current');
	$('#main-nav li:eq(12) a ~ ul').css('display','block');

	 $("#cep").mask("99.999-999");
	   $("#cpf").mask("999.999.999-99");   
	   $("#celular").mask("(99) 9999-9999");
	   $("#data_nasc").mask("99/99/9999"); 

	   function muda(x){
			if(x == '2'){
				$('dt#empresa-label,dd#empresa-element').css('display','block');
				$('dt#instituicao-label,dd#instituicao-element').css('display','none').val(' ');
			}else if(x == '1'){
				$('dt#empresa-label,dd#empresa-element').css('display','none').val(' ');
				$('dt#instituicao-label,dd#instituicao-element').css('display','block');
			}
	 }


		 var value = $("select[id$='tipo']").val();
			muda(value);

		 
		$("select[id$='tipo']").change(function() {
				var val = $(this).val();
				muda(val);
			}); 
});
</script>
<style>
	#finalizar-label{display:none}
	#outro-element,#finalizar-element{width:20%}
</style>
<div class="onecolumn">
	<div class="header">
		<span>Editar Cliente</span>
	</div>
	<br class="clear"/>
	<div class="content">
		<div class="buttons">
			<ul>
				<li>
					<a class="button" title="Voltar para listagem" href="/admin/cliente">
						<img src="/img/icon/back.png"/>
					</a>
				</li>
				<li>
					<a class="button" title="Certificado do <?=$this->cliente['nome'] ?>" href="/admin/certificado/export?nome=<?=$this->cliente['nome'] ?>">
						<img src="/img/document-stamp.png"/>
					</a>
				</li>
				<li>
					<a class="button" title="Excluir <?=$this->cliente['nome'] ?>" onclick="confirma(<?=$this->cliente['id']?>)" href="#">
						<img src="/img/icon/delete.png"/>
					</a>
				</li>
			</ul>
		</div>
		 <?=$this->form?>
	</div>
</div>
<?php echo $this->headScript()->appendFile($this->baseUrl('/js/jquery.maskedinput-1.3.min.js'))
							  ->appendFile($this->baseUrl('/js/jquery.validate.min.js')); ?>
