<style>
	#finalizar-label{display:none}
	#outro-element,#finalizar-element{width:20%}
</style>
<div class="onecolumn">
	<div class="header">
		<span>Editar Cliente</span>
	</div>
	<br class="clear"/>
	<div class="content">
		<div class="buttons">
			<ul>
				<li>
					<a class="button" title="Voltar para listagem" href="/admin/cliente">
						<img src="/img/icon/back.png"/>
					</a>
				</li>
				<li>
					<a class="button" title="Certificado do <?=$this->cliente['nome'] ?>" href="/admin/certificado/export?nome=<?=$this->cliente['nome'] ?>">
						<img src="/img/document-stamp.png"/>
					</a>
				</li>
				<li>
					<a class="button" title="Excluir <?=$this->cliente['nome'] ?>" onclick="confirma(<?=$this->cliente['id']?>)" href="#">
						<img src="/img/icon/delete.png"/>
					</a>
				</li>
			</ul>
		</div>
		 <?=$this->form?>
	</div>
</div>
